version: "3.7"
services: 

  nginx:
    container_name: nginx
    build: requirements/nginx
    volumes:
      - wordpress_volume:/var/www/wordpress 
    depends_on:
      - wordpress
    ports:
      - "433:433"
    networks:
      - wp
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - wp
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    depends_on: 
      - mariadb
    networks:
      - wp
    expose:
      - "9000"
    volumes:
      - wordpress_volume:/var/www/wordpress
    restart: always

networks:
  wp:

volumes: 
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress_volume
      o: bind
  mariadb_volume: 
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb_volume
      o: bind
